"""source code scan column added!

Revision ID: 464300538958
Revises: ceab2d85f85d
Create Date: 2024-11-04 12:16:23.615001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464300538958'
down_revision = 'ceab2d85f85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_code_scan', sa.Text(), nullable=True))
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulns', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('source_code_scan')

    # ### end Alembic commands ###
