"""Vulns tablosu için model güncellemesi

Revision ID: 99d367dcde6a
Revises: 
Create Date: 2024-11-03 15:28:43.909724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d367dcde6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulns', sa.Column('apk_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulns', 'apk_id')
    # ### end Alembic commands ###
