"""Vulns tablosu için model güncellemesi

Revision ID: ceab2d85f85d
Revises: 99d367dcde6a
Create Date: 2024-11-04 10:49:20.759237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceab2d85f85d'
down_revision = '99d367dcde6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulns', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulns', 'date_created')
    # ### end Alembic commands ###
